apiVersion: apps/v1
kind: Deployment
metadata:
  name: back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back
  template:
    metadata:
      labels:
        app: back
    spec:
      containers:
        - name: mongo
          image: mongo:latest
          command:
            - mongod
            - "--bind_ip"
            - "0.0.0.0"
          ports:
          - containerPort: 27017
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  type: NodePort
  ports:
    - name: 'mongo'
      port: 27017
  selector:
    app: back

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      imagePullSecrets:
        - name: registry-creds
      containers:
        - name: node
          image: examplerodrigounir.azurecr.io/app:casopractico2
          ports:
          - containerPort: 3000
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: node
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: node


